### ISSUE TITLE
Gitbook?

### ISSUE THREAD

**Issue by HyperSimon** [ictar/python-doc#63]
就python 常规文档这一块来讲，有没有考虑过用gitbook？因为现在阅读起来不是很方便，也不容易和官方的doc进行对比和同步。

**Comment by ictar** [comment]
@HyperSimon 这个想法不错，我找个时间弄下。

**Comment by ictar** [comment]
已经同步至gitbook: https://ictar.gitbooks.io/python-doc-zh/
