### ISSUE TITLE
想尝试翻译一下Django的文档看到现在的版本已经是1.11了，是不是要更新一下

### ISSUE THREAD

**Issue by zhufree** [ictar/python-doc#69]
RT

**Comment by ictar** [comment]
@zhufree Django文档太庞大了，个人感觉要弄起精力不足，但是非常非常欢迎有兴趣的小伙伴commit

**Comment by zhufree** [comment]
嗯，我也觉得，就当业余的做一下，顺便还可以学学英语，有段时间没用Django了学习一下最新版本
