### ISSUE TITLE
想问下你们都是怎么翻译的（翻译工具这种）

### ISSUE THREAD

**Issue by zhufree** [ictar/python-doc#70]
直接对着原文写还是用翻译平台？看了几个翻译平台网站各有特色。。。现在在用google translate toolkit。
以及多少进度提交一次pull request比较好呢

**Comment by lujun9972** [comment]
翻译平台？那是什么高级玩意？

**Comment by zhufree** [comment]
就是多人协作翻译大型项目的那种，有专业术语表，提供初步机翻，支持很多种文件格式....
看了一下有crowdin,onesky,google transalte toolkit这几个网站比较全面，之前还用过weblate

**Comment by ictar** [comment]
@zhufree

**Comment by ictar** [comment]
@zhufree 你这么一提，我就略表惭愧了。一开始是对着google translate自己翻的，到后期是对着转成的markdown文件直接翻的。
提交的话倒是没什么限制，建议提交完成的译文，即不半中半英的文章。

**Comment by lujun9972** [comment]
果然强悍,求教....

**Comment by zhufree** [comment]
我尝试着转md没成功，就还是把网址输到google translate toolkit让它自动导入了。。。之前用过weblate所以知道有这么一些东西，不过一般适用于很多人的大型翻译项目（如果是各自翻译文章的话感觉优势不大），具体的话百度一下就能找到那些网站了。

**Comment by ictar** [comment]
我是用html2text这个直接转html的。

**Comment by lujun9972** [comment]
pandoc,你值得拥有~~

**Comment by i18nsite** [comment]
分享一下我写的markdown翻译、建站工具

→ [https://i18n.site](//i18n.site)

目前，实现了两个开源的命令行工具:

* `i18` : MarkDown 命令行翻译工具
* `i18n.site` : 多语言静态文档站生成器，**为阅读体验而优化**

翻译，能完美保持`Markdown`的格式。能识别文件修改，只译有改动的文件。

译文可编辑；修改原文，再次机器翻译时，不会覆盖译文的人工修改(如果原文此段未修改)。

**Comment by 999999VVV** [comment]
来件已收到，确认后会回复给你哦
